# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pbureera <pbureera@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/10/18 23:03:01 by pbureera          #+#    #+#              #
#    Updated: 2023/01/19 12:34:14 by pbureera         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME 	= libft.a
SRCS 	= ft_isalnum.c ft_isdigit.c ft_all_isdigit.c ft_memcpy.c ft_putchar_fd.c\
		ft_putstr_fd.c ft_strdup.c ft_strlcpy.c ft_strncmp.c ft_strtrim.c\
		ft_toupper.c ft_bzero.c ft_isalpha.c ft_isprint.c ft_memchr.c\
		ft_memmove.c ft_putendl_fd.c ft_split.c ft_strjoin.c ft_strlen.c\
		ft_strnstr.c ft_substr.c ft_atoi.c ft_calloc.c ft_isascii.c ft_itoa.c\
		ft_memcmp.c ft_memset.c ft_putnbr_fd.c ft_strchr.c ft_strlcat.c\
		ft_strmapi.c ft_strrchr.c ft_tolower.c ft_strcmp.c ft_lstnew.c \
		ft_lstadd_front.c ft_atoi_long.c ft_lstsize.c ft_lstlast.c ft_lstadd_back.c\
		ft_lstclear.c ft_lstiter.c ft_lstmap.c ft_striteri.c ft_strjoin_all.c\
		ft_lstprint_type.c ft_lstadd.c ft_lstjoin.c get_next_line_utils.c \
		get_next_line.c

OBJS 	= ${SRCS:.c=.o}

SRCS_B	= ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstlast.c\
		ft_lstadd_back.c ft_lstdelone.c ft_lstclear.c ft_lstiter.c ft_lstmap.c

OBJS_B	= ${SRCS_B:.c=.o}

HEADER	= ./

CC 		= cc

CFLAGS 	= -Wall -Wextra -Werror

.c.o:
			@${CC} ${CFLAGS} -I ${HEADER} -c $< -o $(<:.c=.o)

$(NAME):	${OBJS} ${OBJS_B}
			@ar rc ${NAME} ${OBJS} ${OBJS_B}

all: 		${NAME}

clean:
			@rm -rf ${OBJS} ${OBJS_B}

fclean: 	clean
			@rm -rf $(NAME)

re:			fclean all

.PHONY: all clean fclean re bonus
